### ISSUE TITLE
An option to choose between the search provider?

### ISSUE THREAD

**Issue by inputsh** [udaiarora/Elegant-New-Tab#3]
Should we be limited to using Google while we search inside of this extension?

So I'm thinking about a dropdown menu behind the search icon that will have a few different search providers available.

My suggestion: Google, DuckDuckGo, Yahoo, Bing and maybe Wikipedia?

**Comment by udaiarora** [comment]
Yeah that was on the list of things I needed to do. Not really getting time though. Feel free to contribute- otherwise I should get around to it some time next week.
